name: "Setup clang-format"
description: "Install a specific clang-format version"
inputs:
  clang-format-version:
    required: true
    description: "Version of clang-format"
runs:
  using: composite
  steps:
    - name: ðŸ› ï¸ Install pipx
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get update && sudo apt-get install -y pipx
      env:
        DEBIAN_FRONTEND: "noninteractive"
      shell: sh

    - name: ðŸ› ï¸ Install clang-format
      run: |
        mkdir -p "$PIPX_BIN_DIR"
        pipx install "clang-format==${{ inputs.clang-format-version }}.*"
      env:
        PIPX_BIN_DIR: "${{ github.workspace }}/.clang-format/bin"
      shell: sh

    - name: ðŸ› ï¸ Add clang-format to PATH
      run: echo "${{ github.workspace }}/.clang-format/bin" >> "$GITHUB_PATH"
      shell: sh
